import {service,storage} from './api.js';
import {t,language,setLanguage,proximity,unavailable,liveUnavailable} from './i18n.js';
import {$,el,today,time,fullTime,status,badge,empty,meta,errorBox,field,events,fresh} from './view.js';
const state={page:'home',tab:'timeline',train:null,date:today(),live:null,schedule:null,coaches:null,full:false,epoch:0,seq:{},busy:new Set(),results:null,routeResults:null,station:null,stationLive:null,stationDetails:false};
const picks=new Map();
const valid=(key,token)=>state.seq[key]===token;
const begin=key=>(state.seq[key]=(state.seq[key]||0)+1);
const loading=target=>{$(target).replaceChildren(el('p',t('जानकारी आ रही है…','Loading…'),'loading'));};
const button=(text,fn,cls='secondary')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const speed=n=>Number.isFinite(n)?n+' km/h':null;
function theme(dark){document.documentElement.dataset.theme=dark?'dark':'light';$('dark-switch').checked=dark;storage.set('rail-theme',dark?'dark':'light');}
theme(storage.get('rail-theme','light')==='dark');$('theme-toggle').onclick=()=>theme(document.documentElement.dataset.theme!=='dark');$('dark-switch').onchange=e=>theme(e.target.checked);
$('language').value=language;setLanguage(language);
$('journey-date').value=today();$('endpoint').value=service.base;
let connected=false;
function connection(){ $('connection').textContent=connected?t('RailRadar • अपडेट का समय देखें','RailRadar • Check update times'):liveUnavailable(); }
async function connect(){const token=begin('config');try{const c=await service.config();if(valid('config',token)){connected=c.liveConnected===true&&c.version>=9.2;}}catch{if(valid('config',token))connected=false;}connection();}
$('settings-form').onsubmit=async e=>{e.preventDefault();try{service.configure($('endpoint').value.trim());reset();await connect();$('settings-message').textContent=connected?t('कनेक्ट हो गया।','Connected.'):liveUnavailable();}catch{$('settings-message').textContent=t('सही HTTPS सर्वर पता भरें।','Enter a valid HTTPS server address.');}};
function reset(){for(const k of Object.keys(state.seq))begin(k);state.busy.clear();state.train=null;state.live=null;state.coaches=null;state.schedule=null;state.results=null;state.routeResults=null;state.station=null;state.stationLive=null;state.stationDetails=false;for(const id of ['route-results','train-results','coach-results','station-results','station-error'])$(id).replaceChildren();$('train-content').hidden=true;$('train-empty').hidden=false;}
function navigate(){const p=location.hash.slice(1)||'home';state.page=['home','search','live','station-live','more'].includes(p)?p:'home';document.querySelectorAll('[data-page]').forEach(n=>n.hidden=n.dataset.page!==state.page);document.querySelectorAll('[data-nav]').forEach(n=>n.setAttribute('aria-current',n.dataset.nav===state.page?'page':'false'));window.scrollTo(0,0);}
addEventListener('hashchange',navigate);navigate();
// Navigation shortcuts reuse the Home forms; result screens never duplicate them.
for(const link of document.querySelectorAll('[data-nav="search"],#train-empty a'))link.onclick=e=>{e.preventDefault();location.hash='home';state.page='home';navigate();requestAnimationFrame(()=>{const input=$('train-query');input.focus({preventScroll:true});input.closest('section.card').scrollIntoView({block:'center',behavior:'smooth'});});};

function setPick(id,s){picks.set(id,s);$(id).value=s.name+' ('+s.code+')';$(id+'-options').replaceChildren();$(id).setAttribute('aria-expanded','false');}
function requirePick(id){if(picks.has(id))return picks.get(id);const code=$(id).value.trim().toUpperCase();if(/^[A-Z0-9]{1,10}$/.test(code))return {code,name:code};throw Error('station');}
function setupPicker(id){let timer,seq=0,controller;const input=$(id),list=$(id+'-options');input.oninput=()=>{picks.delete(id);clearTimeout(timer);controller?.abort();const token=++seq;list.replaceChildren();const q=input.value.trim();input.setAttribute('aria-expanded','false');if(q.length<2)return;timer=setTimeout(async()=>{controller=new AbortController();try{const w=await service.stationSearch(q,controller.signal);if(token!==seq)return;list.replaceChildren();input.setAttribute('aria-expanded','true');for(const s of w.data){const b=button(s.name+' • '+s.code,()=>{seq++;setPick(id,s);input.focus();},'option');b.setAttribute('role','option');b.append(el('small',s.city||unavailable()));list.append(b);}if(!w.data.length)list.append(el('p',t('कोई स्टेशन नहीं मिला','No stations found'),'option-message'));}catch(e){if(token===seq&&e.name!=='AbortError')list.replaceChildren(el('p',liveUnavailable(),'option-message'));}},450);};input.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();list.querySelector('button')?.focus();}if(e.key==='Escape'){seq++;list.replaceChildren();input.setAttribute('aria-expanded','false');}};list.onkeydown=e=>{const bs=[...list.querySelectorAll('button')],i=bs.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();bs[(i+(e.key==='ArrowDown'?1:bs.length-1))%bs.length]?.focus();}if(e.key==='Escape'){list.replaceChildren();input.focus();input.setAttribute('aria-expanded','false');}};document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target)){list.replaceChildren();input.setAttribute('aria-expanded','false');}});}
['from','to'].forEach(setupPicker);
$('route-swap').onclick=()=>{const from=$('from').value,to=$('to').value;const fp=picks.get('from'),tp=picks.get('to');$('from').value=to;$('to').value=from;picks.delete('from');picks.delete('to');if(tp)picks.set('from',tp);if(fp)picks.set('to',fp);};
const HISTORY_KEY='rail-search-history-v98';
function readHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
function writeHistory(item){const old=readHistory().filter(x=>!(x.type===item.type&&x.key===item.key));old.unshift({...item,time:Date.now()});localStorage.setItem(HISTORY_KEY,JSON.stringify(old.slice(0,10)));renderHistory();}
function renderHistory(){const target=$('search-history');if(!target)return;const rows=readHistory();target.replaceChildren();if(!rows.length){target.append(el('p',t('आपकी हाल की खोज यहाँ दिखाई देंगी।','Your recent searches will appear here.'),'micro'));return;}for(const r of rows){const b=button('',()=>{if(r.type==='route'){const [a,bv]=(r.key||'').split('→');$('from').value=a||'';$('to').value=bv||'';picks.delete('from');picks.delete('to');between();}else if(r.type==='train'){searchTrains(r.key)}else if(r.type==='station'){const inp=$('home-live-station');inp.value=r.name||r.key;openHomeStation(r.code||r.key);}},'history-item');b.append(el('span',r.type==='route'?'↔':r.type==='train'?'🚆':'📍','history-type'),el('span',r.label||r.key,'history-label'),el('span','›','history-arrow'));target.append(b);}}
function clearHistory(){localStorage.removeItem(HISTORY_KEY);renderHistory();}
$('clear-history').onclick=clearHistory;
function openHomeStation(code){location.hash='station-live';const found=state.station;const inp=$('live-station');inp.value=code;state.station={code,name:code};$('selected-live-station').hidden=false;$('selected-live-station').textContent=code;loadLiveStation();}
function setupHomeStationSearch(){const input=$('home-live-station'),list=$('home-live-station-options');let timer,seq=0,controller;input.oninput=()=>{clearTimeout(timer);controller?.abort();const token=++seq;list.replaceChildren();input.setAttribute('aria-expanded','false');const q=input.value.trim();if(q.length<2)return;timer=setTimeout(async()=>{controller=new AbortController();try{const w=await service.stationSearch(q,controller.signal);if(token!==seq)return;for(const st of w.data){const b=button(st.name+' • '+st.code,()=>{input.value=st.name+' ('+st.code+')';input.dataset.code=st.code;input.dataset.name=st.name;list.replaceChildren();input.setAttribute('aria-expanded','false');},'option');b.setAttribute('role','option');b.append(el('small',st.city||unavailable()));list.append(b);}input.setAttribute('aria-expanded',w.data.length?'true':'false');if(!w.data.length)list.append(el('p',t('कोई स्टेशन नहीं मिला','No stations found'),'option-message'));}catch(e){if(e.name!=='AbortError')list.replaceChildren(el('p',liveUnavailable(),'option-message'));}},300);};document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target)){list.replaceChildren();input.setAttribute('aria-expanded','false')}});$('home-station-form').onsubmit=e=>{e.preventDefault();const code=input.dataset.code||input.value.trim().toUpperCase();if(!code)return;writeHistory({type:'station',key:code,code,name:input.dataset.name||input.value,label:(input.dataset.name||input.value)+' • '+code});openHomeStation(code);};}
setupHomeStationSearch();renderHistory();
function runDays(days){const names={Mon:['सोम','Mon'],Tue:['मंगल','Tue'],Wed:['बुध','Wed'],Thu:['गुरु','Thu'],Fri:['शुक्र','Fri'],Sat:['शनि','Sat'],Sun:['रवि','Sun']};return days?.length?days.map(d=>{const key=String(d).slice(0,3).toLowerCase();const a=names[key.charAt(0).toUpperCase()+key.slice(1)];return a?t(...a):d;}).join(' · '):unavailable();}
function resultList(id,w,date){const target=$(id);target.replaceChildren(el('p',meta(w),'micro'));if(!w.data.length)return empty(target,t('कोई ट्रेन नहीं मिली।','No trains found.'));for(const r of w.data){const b=button('',()=>{let start=r.journeyDate||today();if(!r.journeyDate&&date&&Number.isInteger(r.boardingDay)){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(r.boardingDay-1));start=d.toISOString().slice(0,10);}openTrain(r.number,start);},'search-result');b.append(el('h3',r.number+' • '+r.name),el('small',(r.from||'—')+' → '+(r.to||'—')),el('small',t('चलने के दिन: ','Running days: ')+runDays(r.runDays)));if(r.arrival||r.departure)b.append(el('small',t('प्रस्थान ','Departure ')+time(r.departure)+' • '+t('आगमन ','Arrival ')+time(r.arrival)));target.append(b);}}

function setupLiveStationPicker(){
 let timer,seq=0,controller;const input=$('live-station'),list=$('live-station-options');
 input.oninput=()=>{state.station=null;clearTimeout(timer);controller?.abort();const token=++seq;list.replaceChildren();input.setAttribute('aria-expanded','false');const q=input.value.trim();if(q.length<2)return;
 timer=setTimeout(async()=>{controller=new AbortController();try{const w=await service.stationSearch(q,controller.signal);if(token!==seq)return;list.replaceChildren();input.setAttribute('aria-expanded','true');
 for(const st of w.data){const b=button(st.name+' • '+st.code,()=>{seq++;state.station=st;input.value=st.name+' ('+st.code+')';list.replaceChildren();input.setAttribute('aria-expanded','false');$('selected-live-station').hidden=false;$('selected-live-station').textContent=st.name+' • '+st.code;loadLiveStation();},'option');b.setAttribute('role','option');b.append(el('small',st.city||unavailable()));list.append(b);}
 if(!w.data.length)list.append(el('p',t('कोई स्टेशन नहीं मिला','No stations found'),'option-message'));
 }catch(e){if(token===seq&&e.name!=='AbortError')list.replaceChildren(el('p',liveUnavailable(),'option-message'));}},350);
 };
 input.onkeydown=e=>{if(e.key==='Escape'){seq++;list.replaceChildren();input.setAttribute('aria-expanded','false');}};
 document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target)){list.replaceChildren();input.setAttribute('aria-expanded','false');}});
}
function stationStatus(row){
 if(row.visitKind==='near')return row.currentLocation?('📍 '+t('ट्रेन अभी ','Train is currently ')+row.currentLocation):'📍 '+t('ट्रेन स्टेशन पर है','Train is currently at this station');
 if(row.currentLocation&&row.next) return '🚆 '+row.currentLocation+' → '+row.next.name;
 if(row.lastReportedStation&&row.next) return '🚆 '+row.lastReportedStation+' → '+row.next.name;
 return '🚆 '+t('अगले स्टेशन की ओर','Running toward the station');
}
function stationEta(row){if(row.visitKind==='near')return t('अभी स्टेशन पर','At station now');const v=row.expectedArrival||row.expectedPassingTime||row.visitTime;const ms=Date.parse(v);if(!Number.isFinite(ms))return unavailable();const mins=Math.max(0,Math.round((ms-Date.now())/60000));if(mins<1)return t('1 मिनट से कम','Less than 1 min');return mins+' '+t('मिनट में','min');}
function renderRunDays(days){
 const wrap=el('div','','run-days');const all=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];for(const d of all){const b=el('span',d);b.className=days?.some(x=>String(x).slice(0,3).toLowerCase()===d.toLowerCase())?'running-day':'faded-day';wrap.append(b);}return wrap;
}
function stationCard(row){
 const card=el('article','','station-train-card'),head=el('div','','station-card-head'),title=el('div');
 const trainButton=el('button','',()=>openTrain(row.number,row.journeyDate||today(),{stationDetails:true}),'train-link station-train-identity');
 const nameEl=el('span',row.name||unavailable(),'station-train-name');
 const numberEl=el('span',t('Train No. ','Train No. ')+(row.number||unavailable()),'station-train-number');
 trainButton.append(nameEl,numberEl);
 title.append(trainButton);
 title.append(el('small',row.to?('→ '+row.to):''));
 head.append(title,el('span',stationEta(row),'station-eta'));card.append(head);
 const live=el('div','','station-live-status '+(row.visitKind==='near'?'at-station':'between-stations'));live.textContent=stationStatus(row);card.append(live);
 const times=el('div','','station-times');
 const arr=row.visitKind==='near'?(row.actualArrival||row.expectedArrival):(row.expectedArrival||row.expectedPassingTime||row.visitTime);
 const dep=row.expectedDeparture;
 times.append(field(t('आगमन','Arrival'),time(arr)),field(t('प्रस्थान','Departure'),time(dep)),field(t('देरी','Delay'),status(row.delayMinutes).label,status(row.delayMinutes).cls),field(t('प्लेटफॉर्म','Platform'),row.platform??unavailable()));
 card.append(times);
 const metaRow=el('div','','station-card-meta');metaRow.append(el('span',t('Destination: ','Destination: ')+(row.to||unavailable())),el('span',t('Current: ','Current: ')+(row.currentLocation||row.lastReportedLocation||unavailable())));card.append(metaRow,renderRunDays(row.runDays));
 const detail=button(t('ट्रेन विवरण →','Train details →'),()=>openTrain(row.number,row.journeyDate||today(),{stationDetails:true}),'secondary');detail.classList.add('wide');card.append(detail);return card;
}
async function loadLiveStation(){
 if(!state.station||state.busy.has('station'))return;const token=begin('station');state.busy.add('station');$('station-refresh').disabled=true;loading('station-results');$('station-error').replaceChildren();
 try{const w=await service.liveStation(state.station.code,0);if(!valid('station',token))return;state.stationLive=w;$('station-meta').textContent=meta(w);const rows=w.data.rows||[];$('station-results').replaceChildren();
 if(!rows.length){empty($('station-results'),t('Live data currently unavailable. Please try again later.','Live data currently unavailable. Please try again later.'));return;}
 rows.sort((x,y)=>Date.parse(x.visitTime||'9999')-Date.parse(y.visitTime||'9999')).forEach(r=>$('station-results').append(stationCard(r)));
 }catch(e){if(valid('station',token))errorBox($('station-error'),e,loadLiveStation);}finally{if(valid('station',token)){state.busy.delete('station');$('station-refresh').disabled=false;}}
}
$('station-refresh').onclick=loadLiveStation;
setupLiveStationPicker();
async function searchTrains(q){if(q)writeHistory({type:'train',key:q,label:q});const token=begin('search');location.hash='search';$('train-query').value=q;loading('train-results');try{const w=await service.trainSearch(q);if(!valid('search',token))return;state.results=w;resultList('train-results',w);}catch(e){if(valid('search',token))errorBox($('train-results'),e,()=>searchTrains(q));}}
$('train-search-form').onsubmit=e=>{e.preventDefault();searchTrains($('train-query').value.trim());};
async function between(){const token=begin('between');try{const from=requirePick('from'),to=requirePick('to'),date=today();if(from.code===to.code){empty($('route-results'),t('दो अलग स्टेशन चुनें।','Choose two different stations.'));return;}writeHistory({type:'route',key:from.code+'→'+to.code,label:from.name+' → '+to.name});loading('route-results');const w=await service.get('/api/between',{from:from.code,to:to.code,date});if(!valid('between',token))return;state.routeResults={w,date};resultList('route-results',w,date);}catch(e){if(valid('between',token))errorBox($('route-results'),e,between);}}
$('between-form').onsubmit=e=>{e.preventDefault();between();};
function nearBox(near,last,stamp){const box=el('div','','location-card');const icon=el('img','','location-train-icon');icon.src='./icon-192.png';icon.alt=t('ट्रेन की वर्तमान स्थिति','Current train position');box.append(icon);if(near&&fresh(stamp))box.append(el('strong','📍 '+near.stationName,'near-station'),el('small',proximity(near.proximity)+' • '+near.distanceKm+' km'));else box.append(el('small',t('आखिरी दर्ज स्टेशन','Last reported station')),el('strong',last||unavailable()));return box;}
async function loadTrainMap(){if(!state.train||!state.date)return;const target=$('train-map');target.replaceChildren(el('p',t('मैप आ रहा है…','Loading map…'),'loading'));try{const src=service.mapUrl(state.train,state.date,10)+'&v='+Math.floor(Date.now()/30000);const img=new Image();img.alt=t('वर्तमान ट्रेन लोकेशन का मैप','Map showing the current train location');img.loading='lazy';img.src=src;img.onload=()=>{target.replaceChildren(img);};img.onerror=()=>{target.replaceChildren(el('p',t('ट्रेन की live location अभी उपलब्ध नहीं है।','Live train location is currently unavailable.'),'error'));};}catch(e){target.replaceChildren(el('p',t('ट्रेन की live location अभी उपलब्ध नहीं है।','Live train location is currently unavailable.'),'error'));}}
function showTab(tab){state.tab=tab;document.querySelectorAll('[data-train-panel]').forEach(p=>p.hidden=p.dataset.trainPanel!==tab);document.querySelectorAll('[data-train-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.trainTab===tab)));if(tab==='map')loadTrainMap();}

for(const b of document.querySelectorAll('[data-train-tab]'))b.onclick=()=>showTab(b.dataset.trainTab);
function openTrain(number,date=today(),options={}){state.stationDetails=options.stationDetails===true;for(const k of ['train','coach','geometry','schedule'])begin(k);state.busy.delete('train');state.train=number;state.date=date;state.live=null;state.schedule=null;state.coaches=null;state.full=false;state.geometry=null;$('journey-date').value=date;$('train-content').hidden=false;$('train-empty').hidden=true;$('train-title').textContent=number;for(const id of ['train-route','train-stats','current-location','timeline','coach-results','coach-station','train-meta','train-error'])$(id).replaceChildren();showTab('timeline');location.hash='live';loadTrain();}
function renderRoute(){const d=state.live?.data;if(!d)return;const rows=d.stations||[],current=rows.findIndex(s=>s.isCurrent);$('full-route').textContent=state.stationDetails?(state.full?t('केवल ठहराव दिखाएँ','Show stops only'):t('Show all stations','Show all stations')):(state.full?t('गुजर चुके स्टेशन छुपाएँ','Hide Passed Stations'):t('पूरा रूट देखें','Show Full Route'));$('timeline').replaceChildren();if(current<0&&!state.full){$('timeline').append(el('p',t('वर्तमान स्टेशन की पुष्टि नहीं है; आने वाले स्टेशन दिखाए गए हैं।','Current station is unconfirmed; showing upcoming stations.'),'micro'));}
const position=d.location?.position;let positionInfo=null;if(position&&Array.isArray(rows)){const candidates=rows.map((s,i)=>({s,i})).filter(x=>Number.isFinite(x.s.lat)&&Number.isFinite(x.s.lng));let best=null;for(let i=0;i<candidates.length-1;i++){const a=candidates[i],b=candidates[i+1],dx=b.s.lng-a.s.lng,dy=b.s.lat-a.s.lat,len=dx*dx+dy*dy;if(!len)continue;const f=Math.max(0,Math.min(1,((position.lng-a.s.lng)*dx+(position.lat-a.s.lat)*dy)/len));const px=a.s.lng+f*dx,py=a.s.lat+f*dy,dist=(position.lng-px)**2+(position.lat-py)**2;if(!best||dist<best.dist)best={a,b,f,dist};}if(best)positionInfo=best;}
for(const [i,s]of rows.entries()){if(state.stationDetails&&!state.full&&!s.isHalt)continue;if(!state.stationDetails&&!state.full&&(current>=0?i<current:['departed','skipped'].includes(s.rawStatus)))continue;const near=d.location?.near?.stationCode===s.code&&fresh(state.live.updatedAt);const row=el('article','','timeline-row'+(s.isHalt?' halt':'')+(near?' current':'')),center=el('div','','timeline-center');if(near){const icon=el('img','','timeline-train-icon');icon.src='./icon-192.png';icon.alt=t('ट्रेन की वर्तमान स्थिति','Current train position');center.append(icon);}center.append(el('h3',s.name,near?'near-station':''),el('p',s.code+' • '+(s.distance??'—')+' km'),el('p',t('प्लेटफॉर्म ','Platform ')+(s.platform??'—')));if(near)center.append(el('strong',proximity(d.location.near.proximity),'current-label'));else center.append(el('small',proximity(s.rawStatus)));if(s.isHalt){center.append(el('small',t('● ठहराव','● Scheduled stop'),'stop-badge'));const a=s.arrival?.scheduled||s.arrival?.expected,d=s.departure?.scheduled||s.departure?.expected;if(a&&d){const am=Date.parse(a),dm=Date.parse(d);if(Number.isFinite(am)&&Number.isFinite(dm)&&dm>=am)center.append(el('small',t('ठहराव: ','Halt: ')+Math.round((dm-am)/60000)+' '+t('मिनट','min'),'stop-badge'));}}else if(state.stationDetails&&!state.full)continue;for(const key of ['arrival','departure']){const ev=s[key],cell=el('div','','time-cell');cell.append(el('span',time(ev?.scheduled),'normal-time'),el('small',(ev?.actual?t('दर्ज ','Actual '):t('संभावित ','Expected '))+time(ev?.actual||ev?.expected),'normal-time'));const delay=s[key==='arrival'?'delayArrival':'delayDeparture'];if(Number.isFinite(delay))cell.append(el('small',status(delay).label,status(delay).cls));if(key==='arrival')row.append(cell,center);else row.append(cell);} $('timeline').append(row);}if(positionInfo&&fresh(state.live.updatedAt)){const displayed=[...$('timeline').querySelectorAll('.timeline-row')];const aIndex=rows.findIndex(x=>x.code===positionInfo.a.s.code),bIndex=rows.findIndex(x=>x.code===positionInfo.b.s.code);const da=displayed.findIndex(x=>rows.findIndex(r=>r.code===positionInfo.a.s.code)===[...rows].findIndex(r=>r.code===positionInfo.a.s.code));const db=displayed.findIndex(x=>rows.findIndex(r=>r.code===positionInfo.b.s.code)===[...rows].findIndex(r=>r.code===positionInfo.b.s.code));if(aIndex>=0&&bIndex>=0&&displayed.length){const marker=el('div','','timeline-current-marker');const topA=displayed[Math.max(0,da)].offsetTop,topB=displayed[Math.max(0,db)].offsetTop;marker.style.top=Math.round(topA+(topB-topA)*positionInfo.f+18)+'px';marker.append(el('span','🚆','timeline-current-icon'),el('span',t('Current Location','वर्तमान लोकेशन'),'timeline-current-label'));$('timeline').append(marker);}}}
$('full-route').onclick=()=>{state.full=!state.full;renderRoute();};
function renderTrain(){const w=state.live;if(!w)return;const d=w.data,l=d.location||{};$('train-title').textContent=d.train.number+' • '+d.train.name;$('train-route').textContent=d.train.routeName||'';$('train-meta').textContent=meta(w);$('current-location').replaceChildren(nearBox(l.near,l.lastReportedStation,w.updatedAt));$('train-stats').replaceChildren(field(t('अगला स्टेशन','Next station'),l.next),field(t('पिछला स्टेशन','Previous station'),l.previous),field(t('देरी','Delay'),status(d.train.delayMinutes).label,status(d.train.delayMinutes).cls),field(t('गति','Speed'),speed(l.speedKmh)),field(t('स्थिति','Status'),proximity(d.train.status)),field(t('अगले ठहराव पर आगमन','Next halt ETA'),time(d.stations.find(s=>s.isHalt&&s.rawStatus==='upcoming')?.arrival?.expected)));
const selected=$('coach-station').value;$('coach-station').replaceChildren();for(const s of d.stations.filter(s=>s.isHalt)){const o=el('option',s.name+' ('+s.code+')');o.value=s.code;$('coach-station').append(o);}if([...$('coach-station').options].some(o=>o.value===selected))$('coach-station').value=selected;$('coach-load').disabled=!$('coach-station').options.length;const days=d.train.runDays||[];const dayText=days.length?t('चलने के दिन: ','Running days: ')+days.join(' · '):'';if(dayText){$('train-meta').textContent+=' • '+dayText;}renderRoute();}
async function loadTrain(){if(!state.train||state.busy.has('train'))return;const token=begin('train');state.busy.add('train');$('train-refresh').disabled=true;if(!state.live)loading('timeline');try{const w=await service.liveTrain(state.train,state.date);if(!valid('train',token))return;state.live=w;$('train-error').replaceChildren();renderTrain();}catch(e){if(valid('train',token)){errorBox($('train-error'),e,loadTrain);if(state.live)renderTrain();else{empty($('timeline'),liveUnavailable());$('train-error').append(button(t('समय-सारणी देखें','View schedule'),loadSchedule));}}}finally{if(valid('train',token)){state.busy.delete('train');$('train-refresh').disabled=false;}}}
async function loadSchedule(){const token=begin('schedule');try{const w=await service.schedule(state.train);if(!valid('schedule',token))return;state.schedule=w;renderSchedule();}catch(e){if(valid('schedule',token))errorBox($('train-error'),e,loadSchedule);}}
function renderSchedule(){const w=state.schedule;if(!w||state.live)return;$('train-title').textContent=w.data.train.number+' • '+w.data.train.name;$('timeline').replaceChildren(el('p',t('केवल समय-सारणी; लाइव स्थिति नहीं।','Schedule only; not live status.'),'connection'));$('coach-station').replaceChildren();for(const s of w.data.route){const row=el('article','','timeline-row'),center=el('div','','timeline-center');center.append(el('h3',s.name),el('p',s.code));row.append(el('span',time(s.arrival)),center,el('span',time(s.departure)));$('timeline').append(row);if(s.isHalt){const o=el('option',s.name);o.value=s.code;$('coach-station').append(o);}}$('coach-load').disabled=!$('coach-station').options.length;}
$('train-refresh').onclick=loadTrain;$('map-refresh').onclick=loadTrainMap;$('journey-date').onchange=e=>openTrain(state.train,e.target.value);$('today').onclick=()=>openTrain(state.train,today());
const berthTypes={LB:['नीचे की बर्थ','Lower berth'],MB:['बीच की बर्थ','Middle berth'],UB:['ऊपर की बर्थ','Upper berth'],SL:['साइड लोअर','Side lower'],SU:['साइड अपर','Side upper'],WS:['खिड़की सीट','Window seat'],MS:['बीच की सीट','Middle seat'],AS:['गलियारे की सीट','Aisle seat']};
function renderCoaches(){const w=state.coaches;if(!w)return;const target=$('coach-results');target.replaceChildren(el('p',meta(w),'micro'));const list=el('div','','coach-list'),detail=el('div','','berth-detail');function select(c){state.selectedCoach=c.code;detail.replaceChildren(el('h3',c.code+' • '+(c.classType||unavailable())),el('p',t('नंबर और बर्थ स्तर सेवा के blueprint के अनुसार।','Numbers and berth levels follow the provider blueprint.'),'micro'));const b=c.blueprint;if(!b){detail.append(el('p',t('इस कोच की सीट/बर्थ बनावट सेवा से उपलब्ध नहीं है।','Seat/berth layout is unavailable from the provider for this coach.')));return;}if(!b.complete)detail.append(el('p',t('आंशिक blueprint — केवल प्राप्त सीटें दिखाई गई हैं।','Partial blueprint — only supplied seats are shown.'),'micro'));for(const cabin of b.cabins){const row=el('section','','cabin'+(['CC','EC','2S'].includes(c.classType)?' sitting':' sleeping'));row.append(el('h4',t('केबिन / पंक्ति ','Cabin / row ')+cabin.number));const layout=el('div','','berth-layout');for(const [key,label]of [['main',t('मुख्य सीटें','Main seats')],['side',t('साइड सीटें','Side seats')]]){const group=el('div','','berth-group');if(key==='main'&&['1A','2A','EC'].includes(c.classType))group.style.gridTemplateColumns='repeat(2,minmax(0,1fr))';group.setAttribute('aria-label',label);for(const s of cabin[key]){const seat=el('div','','berth berth-'+s.type.toLowerCase());seat.title=berthTypes[s.type]?t(...berthTypes[s.type]):s.type;seat.setAttribute('aria-label',s.number+' '+seat.title);seat.append(el('strong',s.number),el('span',s.type));group.append(seat);}layout.append(group);}row.append(layout);detail.append(row);}detail.append(el('p',Object.entries(berthTypes).map(([k,v])=>k+' = '+t(...v)).join(' · '),'berth-legend'));}for(const c of w.data.coaches){const b=button(c.code+' · '+(c.classType||'—'),()=>{list.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));select(c);},'coach');list.append(b);}target.append(list,detail);if(w.data.coaches[0]){const chosen=w.data.coaches.find(c=>c.code===state.selectedCoach)||w.data.coaches.find(c=>c.blueprint)||w.data.coaches[0];[...list.children].find(n=>n.textContent.startsWith(chosen.code+' ·'))?.setAttribute('aria-pressed','true');select(chosen);}}
async function coaches(){const station=$('coach-station').value;if(!station||!state.train)return;const token=begin('coach');$('coach-load').disabled=true;loading('coach-results');try{const w=await service.coachPosition(state.train,station);if(valid('coach',token)){state.coaches=w;renderCoaches();}}catch(e){if(valid('coach',token))errorBox($('coach-results'),e,coaches);}finally{if(valid('coach',token))$('coach-load').disabled=false;}}
$('coach-form').onsubmit=e=>{e.preventDefault();coaches();};$('coach-station').onchange=()=>{begin('coach');state.coaches=null;$('coach-results').replaceChildren();$('coach-load').disabled=false;};
$('language').onchange=e=>{setLanguage(e.target.value);connection();if(state.results)resultList('train-results',state.results);if(state.routeResults)resultList('route-results',state.routeResults.w,state.routeResults.date);renderTrain();renderSchedule();renderCoaches();document.querySelectorAll('.error').forEach(box=>{box.querySelector('strong').textContent=liveUnavailable();const p=box.querySelector('p');if(p)p.textContent=t('कुछ देर बाद फिर कोशिश करें।','Please retry shortly.');box.querySelector('button').textContent=t('↻ फिर कोशिश करें','↻ Retry');});};
setInterval(()=>{if(document.hidden)return;if(state.live){$('train-meta').textContent=meta(state.live);if(!fresh(state.live.updatedAt)){renderTrain();}}},15000);
setInterval(()=>{if(document.hidden||!$('auto-switch').checked||Date.now()<service.cooldown)return;if(state.page==='live'&&state.tab!=='map'){loadTrain();}},60000);
connect();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

