import {service,storage} from './api.js';
import {t,language,setLanguage,proximity,unavailable,liveUnavailable} from './i18n.js';
import {$,el,today,time,fullTime,status,badge,empty,meta,errorBox,field,events,fresh} from './view.js';
import {drawMap,clearMap,fitMap,resizeMap,configureImagery,changeLayer,searchMap} from './map.js';
const state={page:'home',tab:'timeline',train:null,date:today(),live:null,schedule:null,station:null,board:null,boardType:'halt',behind:null,behindPages:new Map(),coaches:null,full:false,epoch:0,seq:{},busy:new Set(),results:null,routeResults:null};
const picks=new Map();
const valid=(key,token)=>state.seq[key]===token;
const begin=key=>(state.seq[key]=(state.seq[key]||0)+1);
const loading=target=>empty($(target),t('जानकारी आ रही है…','Loading…'));
const button=(text,fn,cls='secondary')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const speed=n=>Number.isFinite(n)?n+' km/h':null;
function theme(dark){document.documentElement.dataset.theme=dark?'dark':'light';$('dark-switch').checked=dark;storage.set('rail-theme',dark?'dark':'light');}
theme(storage.get('rail-theme','light')==='dark');$('theme-toggle').onclick=()=>theme(document.documentElement.dataset.theme!=='dark');$('dark-switch').onchange=e=>theme(e.target.checked);
$('language').value=language;setLanguage(language);
$('boarding-date').value=today();$('journey-date').value=today();$('endpoint').value=service.base;
let connected=false;
function connection(){ $('connection').textContent=connected?t('RailRadar • अपडेट का समय देखें','RailRadar • Check update times'):liveUnavailable(); }
async function connect(){const token=begin('config');try{const c=await service.config();if(valid('config',token)){connected=c.liveConnected===true&&c.version>=8;configureImagery(c.satellite,service.base);}}catch{if(valid('config',token))connected=false;}connection();}
$('settings-form').onsubmit=async e=>{e.preventDefault();try{service.configure($('endpoint').value.trim());reset();await connect();$('settings-message').textContent=connected?t('कनेक्ट हो गया।','Connected.'):liveUnavailable();}catch{$('settings-message').textContent=t('सही HTTPS सर्वर पता भरें।','Enter a valid HTTPS server address.');}};
function reset(){for(const k of Object.keys(state.seq))begin(k);state.train=null;state.live=null;state.board=null;state.behind=null;state.behindPages.clear();state.coaches=null;state.schedule=null;state.results=null;state.routeResults=null;clearMap();for(const id of ['route-results','train-results','station-results','station-notice','behind-results','coach-results'])$(id).replaceChildren();$('train-content').hidden=true;$('train-empty').hidden=false;}
function navigate(){const p=location.hash.slice(1)||'home';state.page=['home','search','station','live','more'].includes(p)?p:'home';document.querySelectorAll('[data-page]').forEach(n=>n.hidden=n.dataset.page!==state.page);document.querySelectorAll('[data-nav]').forEach(n=>n.setAttribute('aria-current',n.dataset.nav===state.page?'page':'false'));if(state.page==='live'&&state.tab==='map')renderMap();window.scrollTo(0,0);}
addEventListener('hashchange',navigate);navigate();
function setPick(id,s){picks.set(id,s);$(id).value=s.name+' ('+s.code+')';$(id+'-options').replaceChildren();$(id).setAttribute('aria-expanded','false');}
function requirePick(id){if(picks.has(id))return picks.get(id);const code=$(id).value.trim().toUpperCase();if(/^[A-Z0-9]{1,10}$/.test(code))return {code,name:code};throw Error('station');}
function setupPicker(id){let timer,seq=0,controller;const input=$(id),list=$(id+'-options');input.oninput=()=>{picks.delete(id);clearTimeout(timer);controller?.abort();const token=++seq;list.replaceChildren();const q=input.value.trim();input.setAttribute('aria-expanded','false');if(q.length<2)return;timer=setTimeout(async()=>{controller=new AbortController();try{const w=await service.stationSearch(q,controller.signal);if(token!==seq)return;list.replaceChildren();input.setAttribute('aria-expanded','true');for(const s of w.data){const b=button(s.name+' • '+s.code,()=>{seq++;setPick(id,s);input.focus();},'option');b.setAttribute('role','option');b.append(el('small',s.city||unavailable()));list.append(b);}if(!w.data.length)list.append(el('p',t('कोई स्टेशन नहीं मिला','No stations found'),'option-message'));}catch(e){if(token===seq&&e.name!=='AbortError')list.replaceChildren(el('p',liveUnavailable(),'option-message'));}},450);};input.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();list.querySelector('button')?.focus();}if(e.key==='Escape'){seq++;list.replaceChildren();input.setAttribute('aria-expanded','false');}};list.onkeydown=e=>{const bs=[...list.querySelectorAll('button')],i=bs.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();bs[(i+(e.key==='ArrowDown'?1:bs.length-1))%bs.length]?.focus();}if(e.key==='Escape'){list.replaceChildren();input.focus();input.setAttribute('aria-expanded','false');}};document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target)){list.replaceChildren();input.setAttribute('aria-expanded','false');}});}
['from','to','home-station','station-query'].forEach(setupPicker);
$('swap').onclick=()=>{const a=$('from').value,b=$('to').value,pa=picks.get('from'),pb=picks.get('to');$('from').value=b;$('to').value=a;picks.delete('from');picks.delete('to');if(pa)picks.set('to',pa);if(pb)picks.set('from',pb);};
function runDays(days){const names={Mon:['सोम','Mon'],Tue:['मंगल','Tue'],Wed:['बुध','Wed'],Thu:['गुरु','Thu'],Fri:['शुक्र','Fri'],Sat:['शनि','Sat'],Sun:['रवि','Sun']};return days?.length?days.map(d=>{const key=String(d).slice(0,3).toLowerCase();const a=names[key.charAt(0).toUpperCase()+key.slice(1)];return a?t(...a):d;}).join(' · '):unavailable();}
function resultList(id,w,date){const target=$(id);target.replaceChildren(el('p',meta(w),'micro'));if(!w.data.length)return empty(target,t('कोई ट्रेन नहीं मिली।','No trains found.'));for(const r of w.data){const b=button('',()=>{let start=r.journeyDate||today();if(!r.journeyDate&&date&&Number.isInteger(r.boardingDay)){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(r.boardingDay-1));start=d.toISOString().slice(0,10);}openTrain(r.number,start);},'search-result');b.append(el('h3',r.number+' • '+r.name),el('small',(r.from||'—')+' → '+(r.to||'—')),el('small',t('चलने के दिन: ','Running days: ')+runDays(r.runDays)));if(r.arrival||r.departure)b.append(el('small',t('प्रस्थान ','Departure ')+time(r.departure)+' • '+t('आगमन ','Arrival ')+time(r.arrival)));target.append(b);}}
async function searchTrains(q){const token=begin('search');location.hash='search';$('train-query').value=q;loading('train-results');try{const w=await service.trainSearch(q);if(!valid('search',token))return;state.results=w;resultList('train-results',w);}catch(e){if(valid('search',token))errorBox($('train-results'),e,()=>searchTrains(q));}}
$('home-train-form').onsubmit=e=>{e.preventDefault();searchTrains($('home-train').value.trim());};$('train-search-form').onsubmit=e=>{e.preventDefault();searchTrains($('train-query').value.trim());};
async function between(){const token=begin('between');try{const from=requirePick('from'),to=requirePick('to'),date=$('boarding-date').value;if(from.code===to.code){empty($('route-results'),t('दो अलग स्टेशन चुनें।','Choose two different stations.'));return;}loading('route-results');const w=await service.get('/api/between',{from:from.code,to:to.code,date});if(!valid('between',token))return;state.routeResults={w,date};resultList('route-results',w,date);}catch(e){if(valid('between',token))errorBox($('route-results'),e,between);}}
$('between-form').onsubmit=e=>{e.preventDefault();between();};
function nearBox(near,last,stamp){const box=el('div','','location-card');if(near&&fresh(stamp))box.append(el('strong','● '+near.stationName,'near-station'),el('small',proximity(near.proximity)+' • '+near.distanceKm+' km'));else box.append(el('small',t('आखिरी दर्ज स्टेशन','Last reported station')),el('strong',last||unavailable()));return box;}
function boardCard(r){const card=el('article','','board-card');card.append(button(r.number+' • '+r.name,()=>openTrain(r.number,r.journeyDate),'train-link'),badge(r.delayMinutes),nearBox(r,r.currentLocation,r.updatedAt));if(r.isHalt===false)card.append(el('span',t('बिना ठहराव • NON-STOP','NON-STOP'),'pill nonstop'));const facts=el('div','','board-times');for(const [label,value]of [[t('निर्धारित आगमन','Scheduled Arrival'),time(r.scheduledArrival)],[t('वास्तविक आगमन','Actual Arrival'),time(r.actualArrival)],[t('संभावित आगमन','Expected Arrival'),time(r.expectedArrival)],[t('निर्धारित प्रस्थान','Scheduled Departure'),time(r.scheduledDeparture)],[t('वास्तविक प्रस्थान','Actual Departure'),time(r.actualDeparture)],[t('संभावित प्रस्थान','Expected Departure'),time(r.expectedDeparture)],[t('प्लेटफॉर्म','Platform'),r.platform],[t('गति','Speed'),speed(r.speedKmh)]])facts.append(field(label,value,'normal-time'));card.append(facts,el('p',meta({updatedAt:r.updatedAt}),'micro'));return card;}
function renderBoard(){const w=state.board;$('station-more').hidden=!w||w.data.nextOffset===null;if(!w)return;const d=w.data;$('station-title').textContent=d.station.name+' • '+d.station.code;$('station-notice').replaceChildren(el('p',t('दायरा: ','Radius: ')+d.radiusKm+' km • '+t('सिर्फ 5 मिनट के भीतर अपडेट हुई, पुष्टि की गई लोकेशन।','Only verified positions updated within 5 minutes.'),'micro'),el('p',t('जाँची गई: ','Checked: ')+d.checked+' / '+d.totalCandidates+t(' संभावित ट्रेनें। API की सूची तक सीमित।',' candidates. Limited to provider coverage.'),'micro'));if(d.failed)$('station-notice').append(el('p',t('कुछ ट्रेनें जाँची नहीं जा सकीं। अपडेट करके फिर कोशिश करें।','Some trains could not be checked. Refresh to retry.'),'late'));const rows=d.rows.filter(r=>fresh(r.updatedAt)&&r.isHalt===(state.boardType==='halt'));$('station-results').replaceChildren(...rows.map(boardCard));if(!rows.length)empty($('station-results'),t('इस जाँच में आसपास की पुष्टि की गई ट्रेन नहीं मिली।','No verified nearby trains in this check.'));}
async function loadStation(more=false){if(!state.station||state.busy.has('station'))return;const token=begin('station'),station=state.station.code,offset=more?state.board?.data.nextOffset:0;if(offset===null)return;state.busy.add('station');$('station-refresh').disabled=true;$('station-more').disabled=true;try{const w=await service.liveStation(station,offset);if(!valid('station',token))return;if(more&&state.board){w.data.rows=[...state.board.data.rows,...w.data.rows].filter((r,i,a)=>a.findIndex(x=>x.number===r.number)===i);w.data.checked+=state.board.data.checked;w.data.failed+=state.board.data.failed;}state.board=w;renderBoard();}catch(e){if(valid('station',token)){errorBox($('station-notice'),e,()=>loadStation(more));$('station-results').replaceChildren();}}finally{state.busy.delete('station');$('station-refresh').disabled=false;$('station-more').disabled=false;}}
function openStation(id){try{state.station=requirePick(id);begin('station');state.busy.delete('station');state.board=null;setPick('station-query',state.station);location.hash='station';loading('station-results');loadStation();}catch{location.hash='station';empty($('station-notice'),t('सूची से स्टेशन चुनें या सही कोड भरें।','Select a station or enter its code.'));}}
$('home-station-form').onsubmit=e=>{e.preventDefault();openStation('home-station');};$('station-form').onsubmit=e=>{e.preventDefault();openStation('station-query');};$('station-refresh').onclick=()=>loadStation();$('station-more').onclick=()=>loadStation(true);$('station-more').hidden=true;
for(const b of document.querySelectorAll('[data-board]'))b.onclick=()=>{state.boardType=b.dataset.board;document.querySelectorAll('[data-board]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderBoard();};
function showTab(tab){$('map-shell').classList.remove('map-expanded');state.tab=tab;document.querySelectorAll('[data-train-panel]').forEach(p=>p.hidden=p.dataset.trainPanel!==tab);document.querySelectorAll('[data-train-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.trainTab===tab)));if(tab==='behind'&&!state.behind)loadBehind();if(tab==='map'){loadTrain();renderMap();$('map-canvas').scrollIntoView({block:'center'});if(!state.behind)loadBehind();}}
for(const b of document.querySelectorAll('[data-train-tab]'))b.onclick=()=>showTab(b.dataset.trainTab);
function openTrain(number,date=today()){for(const k of ['train','behind','coach','geometry','schedule'])begin(k);state.busy.delete('train');state.busy.delete('behind');state.train=number;state.date=date;state.live=null;state.schedule=null;state.behind=null;state.behindPages.clear();state.coaches=null;state.full=false;state.geometry=null;clearMap();$('journey-date').value=date;$('train-content').hidden=false;$('train-empty').hidden=true;$('train-title').textContent=number;for(const id of ['train-route','train-stats','current-location','timeline','coach-results','coach-station','behind-results','train-meta','train-error'])$(id).replaceChildren();showTab('timeline');location.hash='live';loadTrain();}
function renderRoute(){const d=state.live?.data;if(!d)return;const rows=d.stations||[],current=rows.findIndex(s=>s.isCurrent);$('full-route').textContent=state.full?t('गुजर चुके स्टेशन छुपाएँ','Hide Passed Stations'):t('पूरा रूट देखें','Show Full Route');$('timeline').replaceChildren();if(current<0&&!state.full){$('timeline').append(el('p',t('वर्तमान स्टेशन की पुष्टि नहीं है; आने वाले स्टेशन दिखाए गए हैं।','Current station is unconfirmed; showing upcoming stations.'),'micro'));}
for(const [i,s]of rows.entries()){if(!state.full&&(current>=0?i<current:['departed','skipped'].includes(s.rawStatus)))continue;const near=d.location?.near?.stationCode===s.code&&fresh(state.live.updatedAt);const row=el('article','','timeline-row'+(s.isHalt?' halt':'')+(near?' current':'')),center=el('div','','timeline-center');center.append(el('h3',s.name,near?'near-station':''),el('p',s.code+' • '+(s.distance??'—')+' km'),el('p',t('प्लेटफॉर्म ','Platform ')+(s.platform??'—')));if(near)center.append(el('strong',proximity(d.location.near.proximity),'current-label'));else center.append(el('small',proximity(s.rawStatus)));if(s.isHalt)center.append(el('small',t('● ठहराव','● Scheduled stop'),'stop-badge'));for(const key of ['arrival','departure']){const ev=s[key],cell=el('div','','time-cell');cell.append(el('span',time(ev?.scheduled),'normal-time'),el('small',(ev?.actual?t('दर्ज ','Actual '):t('संभावित ','Expected '))+time(ev?.actual||ev?.expected),'normal-time'));const delay=s[key==='arrival'?'delayArrival':'delayDeparture'];if(Number.isFinite(delay))cell.append(el('small',status(delay).label,status(delay).cls));if(key==='arrival')row.append(cell,center);else row.append(cell);} $('timeline').append(row);}}
$('full-route').onclick=()=>{state.full=!state.full;renderRoute();};
function renderTrain(){const w=state.live;if(!w)return;const d=w.data,l=d.location||{};$('train-title').textContent=d.train.number+' • '+d.train.name;$('train-route').textContent=d.train.routeName||'';$('train-meta').textContent=meta(w);$('current-location').replaceChildren(nearBox(l.near,l.lastReportedStation,w.updatedAt));$('train-stats').replaceChildren(field(t('अगला स्टेशन','Next station'),l.next),field(t('पिछला स्टेशन','Previous station'),l.previous),field(t('देरी','Delay'),status(d.train.delayMinutes).label,status(d.train.delayMinutes).cls),field(t('गति','Speed'),speed(l.speedKmh)),field(t('स्थिति','Status'),proximity(d.train.status)),field(t('अगले ठहराव पर आगमन','Next halt ETA'),time(d.stations.find(s=>s.isHalt&&s.rawStatus==='upcoming')?.arrival?.expected)));
const selected=$('coach-station').value;$('coach-station').replaceChildren();for(const s of d.stations.filter(s=>s.isHalt)){const o=el('option',s.name+' ('+s.code+')');o.value=s.code;$('coach-station').append(o);}if([...$('coach-station').options].some(o=>o.value===selected))$('coach-station').value=selected;$('coach-load').disabled=!$('coach-station').options.length;renderRoute();if(state.tab==='map')renderMap();}
async function loadTrain(){if(!state.train||state.busy.has('train'))return;const token=begin('train');state.busy.add('train');$('train-refresh').disabled=true;if(!state.live)loading('timeline');try{const w=await service.liveTrain(state.train,state.date);if(!valid('train',token))return;state.live=w;$('train-error').replaceChildren();renderTrain();}catch(e){if(valid('train',token)){errorBox($('train-error'),e,loadTrain);if(state.live)renderTrain();else{empty($('timeline'),liveUnavailable());$('train-error').append(button(t('समय-सारणी देखें','View schedule'),loadSchedule));}}}finally{state.busy.delete('train');$('train-refresh').disabled=false;}}
async function loadSchedule(){const token=begin('schedule');try{const w=await service.schedule(state.train);if(!valid('schedule',token))return;state.schedule=w;renderSchedule();}catch(e){if(valid('schedule',token))errorBox($('train-error'),e,loadSchedule);}}
function renderSchedule(){const w=state.schedule;if(!w||state.live)return;$('train-title').textContent=w.data.train.number+' • '+w.data.train.name;$('timeline').replaceChildren(el('p',t('केवल समय-सारणी; लाइव स्थिति नहीं।','Schedule only; not live status.'),'connection'));$('coach-station').replaceChildren();for(const s of w.data.route){const row=el('article','','timeline-row'),center=el('div','','timeline-center');center.append(el('h3',s.name),el('p',s.code));row.append(el('span',time(s.arrival)),center,el('span',time(s.departure)));$('timeline').append(row);if(s.isHalt){const o=el('option',s.name);o.value=s.code;$('coach-station').append(o);}}$('coach-load').disabled=!$('coach-station').options.length;}
$('train-refresh').onclick=loadTrain;$('journey-date').onchange=e=>openTrain(state.train,e.target.value);$('today').onclick=()=>openTrain(state.train,today());
function behindCard(r){const c=button('',()=>openTrain(r.number,r.journeyDate),'behind-card');c.append(el('h3',r.number+' • '+r.name),nearBox(r.near,r.station,r.updatedAt),el('p',r.distanceMinKm+'–'+r.distanceMaxKm+t(' किमी पीछे • रूट के आधार पर सीमा',' km behind • route-based range')),badge(r.delayMinutes));const facts=el('div','','board-times');for(const [label,value]of [[t('ट्रेन प्रकार','Train type'),r.trainType],[t('गति','Speed'),speed(r.speedKmh)],[t('दिशा','Direction'),t('समान दिशा','Same direction')],[t('अगला स्टेशन','Next station'),r.nextStation],[t('संभावित आगमन','Expected arrival'),time(r.nextHalt?.expectedArrival)]])facts.append(field(label,value));c.append(facts,el('small',meta({updatedAt:r.updatedAt})),el('p',t('पूरा लाइव स्टेटस देखें →','View Full Train Status →')));return c;}
function renderBehind(){
 const d=state.behind?.data;for(const id of ['behind-more','map-more']){const n=$(id);n.hidden=!d||d.resumeOffset===null;n.textContent=t('बाकी जाँच फिर शुरू करें','Resume remaining checks');}if(!d)return;
 const rows=d.items.filter(r=>fresh(r.updatedAt)&&r.distanceMaxKm<=50);
 $('behind-results').replaceChildren(el('p','50 km • '+rows.length+t(' पुष्टि की गई ट्रेनें • जाँची गई: ',' verified trains • Checked: ')+d.checked+' / '+(d.totalCandidates??0),'micro'),...rows.map(behindCard));
 if(state.busy.has('behind'))$('behind-results').prepend(el('p',t('दायरे की सभी उपलब्ध ट्रेनों की जाँच हो रही है…','Checking all available trains in range…'),'micro checking'));
 if(d.failed)$('behind-results').prepend(el('p',t('कुछ जाँचें बाकी हैं। API उपलब्ध होने पर फिर जारी होंगी।','Some checks remain. They will resume when the API is available.'),'late'));
 if(d.boundaryUncertain)$('behind-results').append(el('p',t('कुछ ट्रेनों की दूरी 50 किमी की सीमा के दोनों ओर हो सकती है; उन्हें पुष्टि की गई सूची में नहीं रखा है।','Some distance ranges straddle 50 km and cannot be confirmed inside the radius.'),'micro'));
 if(!rows.length)$('behind-results').append(el('div',t('50 किमी के भीतर ताज़ा और तुलनीय पीछे की ट्रेन नहीं मिली।','No fresh, comparable behind train confirmed within 50 km.'),'empty'));if(state.tab==='map')renderMap();
}
async function loadBehind(resume=false){
 if(!state.train||state.busy.has('behind')||Date.now()<service.cooldown)return;
 const token=begin('behind');let offset=resume?state.behind?.data.resumeOffset:0;if(offset===null)return;if(!resume)state.behindPages.clear();
 state.busy.add('behind');for(const id of ['behind-load','behind-more','map-more'])$(id).disabled=true;
 try{while(offset!==null){
  const w=await service.get('/api/nearby',{train:state.train,date:state.date,offset});if(!valid('behind',token))return;
  state.behindPages.set(offset,w.data);const pages=[...state.behindPages.values()],items=pages.flatMap(p=>p.items).filter((r,i,a)=>a.findIndex(x=>x.number===r.number&&x.journeyDate===r.journeyDate)===i).sort((a,b)=>a.distanceMinKm-b.distanceMinKm);
  const next=w.data.failed?offset:w.data.nextOffset;
  state.behind={...w,data:{...w.data,items,checked:pages.reduce((n,p)=>n+(p.checked||0),0),failed:pages.reduce((n,p)=>n+(p.failed||0),0),boundaryUncertain:pages.reduce((n,p)=>n+(p.boundaryUncertain||0),0),resumeOffset:next}};renderBehind();
  if(w.data.rateLimited)service.cooldown=Date.now()+(w.data.retryAfterSeconds||65)*1000;
  if(w.data.failed||document.hidden||state.page!=='live'||!['behind','map'].includes(state.tab))break;
  if(next!==null&&next<=offset)throw Error('Invalid page cursor');offset=next;
 }
 }catch(e){if(valid('behind',token)){if(state.behind)state.behind.data.resumeOffset=offset;errorBox($('behind-results'),e,()=>loadBehind(true));if(state.tab==='map')$('map-note').textContent=liveUnavailable();}}
 finally{if(valid('behind',token)){state.busy.delete('behind');$('behind-results').querySelector('.checking')?.remove();updateMapMode();for(const id of ['behind-load','behind-more','map-more'])$(id).disabled=false;}}
}
$('behind-load').onclick=()=>loadBehind();$('behind-more').onclick=()=>loadBehind(true);$('map-more').onclick=()=>loadBehind(true);$('behind-more').hidden=true;$('map-more').hidden=true;
const berthTypes={LB:['नीचे की बर्थ','Lower berth'],MB:['बीच की बर्थ','Middle berth'],UB:['ऊपर की बर्थ','Upper berth'],SL:['साइड लोअर','Side lower'],SU:['साइड अपर','Side upper'],WS:['खिड़की सीट','Window seat'],MS:['बीच की सीट','Middle seat'],AS:['गलियारे की सीट','Aisle seat']};
function renderCoaches(){const w=state.coaches;if(!w)return;const target=$('coach-results');target.replaceChildren(el('p',meta(w),'micro'));const list=el('div','','coach-list'),detail=el('div','','berth-detail');function select(c){state.selectedCoach=c.code;detail.replaceChildren(el('h3',c.code+' • '+(c.classType||unavailable())),el('p',t('नंबर और बर्थ स्तर सेवा के blueprint के अनुसार।','Numbers and berth levels follow the provider blueprint.'),'micro'));const b=c.blueprint;if(!b){detail.append(el('p',t('इस कोच की सीट/बर्थ बनावट सेवा से उपलब्ध नहीं है।','Seat/berth layout is unavailable from the provider for this coach.')));return;}if(!b.complete)detail.append(el('p',t('आंशिक blueprint — केवल प्राप्त सीटें दिखाई गई हैं।','Partial blueprint — only supplied seats are shown.'),'micro'));for(const cabin of b.cabins){const row=el('section','','cabin'+(['CC','EC','2S'].includes(c.classType)?' sitting':' sleeping'));row.append(el('h4',t('केबिन / पंक्ति ','Cabin / row ')+cabin.number));const layout=el('div','','berth-layout');for(const [key,label]of [['main',t('मुख्य सीटें','Main seats')],['side',t('साइड सीटें','Side seats')]]){const group=el('div','','berth-group');if(key==='main'&&['1A','2A','EC'].includes(c.classType))group.style.gridTemplateColumns='repeat(2,minmax(0,1fr))';group.setAttribute('aria-label',label);for(const s of cabin[key]){const seat=el('div','','berth berth-'+s.type.toLowerCase());seat.title=berthTypes[s.type]?t(...berthTypes[s.type]):s.type;seat.setAttribute('aria-label',s.number+' '+seat.title);seat.append(el('strong',s.number),el('span',s.type));group.append(seat);}layout.append(group);}row.append(layout);detail.append(row);}detail.append(el('p',Object.entries(berthTypes).map(([k,v])=>k+' = '+t(...v)).join(' · '),'berth-legend'));}for(const c of w.data.coaches){const b=button(c.code+' · '+(c.classType||'—'),()=>{list.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));select(c);},'coach');list.append(b);}target.append(list,detail);if(w.data.coaches[0]){const chosen=w.data.coaches.find(c=>c.code===state.selectedCoach)||w.data.coaches.find(c=>c.blueprint)||w.data.coaches[0];[...list.children].find(n=>n.textContent.startsWith(chosen.code+' ·'))?.setAttribute('aria-pressed','true');select(chosen);}}
async function coaches(){const station=$('coach-station').value;if(!station||!state.train)return;const token=begin('coach');$('coach-load').disabled=true;loading('coach-results');try{const w=await service.coachPosition(state.train,station);if(valid('coach',token)){state.coaches=w;renderCoaches();}}catch(e){if(valid('coach',token))errorBox($('coach-results'),e,coaches);}finally{if(valid('coach',token))$('coach-load').disabled=false;}}
$('coach-form').onsubmit=e=>{e.preventDefault();coaches();};$('coach-station').onchange=()=>{begin('coach');state.coaches=null;$('coach-results').replaceChildren();$('coach-load').disabled=false;};
function renderMap(){if(state.tab!=='map')return;const d=state.live?.data,rows=[...(state.behind?.data.items||[])];if(d)rows.unshift({...d.location,number:d.train.number,name:d.train.name,journeyDate:state.date,delayMinutes:d.train.delayMinutes,nextStation:d.location?.next,nextHalt:{expectedArrival:d.stations.find(s=>s.isHalt&&s.rawStatus==='upcoming')?.arrival?.expected}});drawMap($('map-canvas'),rows,state.geometry,openTrain,$('map-note'));updateMapMode();const available=rows.filter(r=>fresh(r.updatedAt)&&r.position);$('map-list').replaceChildren(...available.map(r=>button(r.number+' • '+r.name,()=>openTrain(r.number,r.journeyDate),'search-result')));if(!state.geometry&&state.train&&!state.busy.has('geometry'))loadGeometry();}
async function loadGeometry(){state.busy.add('geometry');const token=begin('geometry');try{const w=await service.get('/api/geometry',{train:state.train});if(valid('geometry',token)){state.geometry=w.data.coordinates;renderMap();}}catch{if(valid('geometry',token))state.geometry=[];}finally{state.busy.delete('geometry');}}
function updateMapMode(){const active=$('auto-switch').checked&&!document.hidden&&state.page==='live'&&state.tab==='map';$('map-active').checked=$('auto-switch').checked;$('map-mode').textContent=Date.now()<service.cooldown?t('API की सीमा • अपडेट रुका है','API limit • updates paused'):active?t('● सक्रिय • हर 60 सेकंड में अपडेट','● Active • updates every 60 seconds'):t('अपडेट रुका है','Updates paused');}
$('map-active').onchange=e=>{$('auto-switch').checked=e.target.checked;updateMapMode();if(e.target.checked){loadTrain();loadBehind(state.behind?.data.resumeOffset!=null);}};
$('auto-switch').onchange=updateMapMode;
$('map-fit').onclick=()=>fitMap();
$('map-layer').onchange=e=>changeLayer(e.target.value,$('map-note'));
$('map-search').oninput=e=>searchMap(e.target.value,$('map-search-results'));
$('map-legend').onclick=()=>{$('map-legend-text').hidden=!$('map-legend-text').hidden;};
$('map-expand').onclick=()=>{$('map-shell').classList.toggle('map-expanded');$('map-expand').setAttribute('aria-pressed',String($('map-shell').classList.contains('map-expanded')));resizeMap();};
addEventListener('keydown',e=>{if(e.key==='Escape'){$('map-shell').classList.remove('map-expanded');resizeMap();}});
$('map-refresh').onclick=async()=>{await loadTrain();await loadBehind();renderMap();};
$('language').onchange=e=>{setLanguage(e.target.value);connection();if(state.results)resultList('train-results',state.results);if(state.routeResults)resultList('route-results',state.routeResults.w,state.routeResults.date);renderTrain();renderSchedule();renderBoard();renderBehind();renderCoaches();renderMap();document.querySelectorAll('.error').forEach(box=>{box.querySelector('strong').textContent=liveUnavailable();const p=box.querySelector('p');if(p)p.textContent=t('कुछ देर बाद फिर कोशिश करें।','Please retry shortly.');box.querySelector('button').textContent=t('↻ फिर कोशिश करें','↻ Retry');});};
setInterval(()=>{if(document.hidden)return;if(state.live){$('train-meta').textContent=meta(state.live);if(!fresh(state.live.updatedAt)){renderTrain();renderMap();}}if(state.board)renderBoard();if(state.behind?.data.items.some(r=>!fresh(r.updatedAt)))renderBehind();},15000);
setInterval(()=>{if(document.hidden||!$('auto-switch').checked||Date.now()<service.cooldown)return;if(state.page==='station')loadStation();if(state.page==='live'){loadTrain();if(['behind','map'].includes(state.tab))loadBehind(state.behind?.data.resumeOffset!=null);}},60000);
connect();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
