const $=id=>document.getElementById(id);
$('date').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let lastQuery='';
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e}
function render(d){const t=d.train;if(!t||!t.number)throw Error('सर्वर ने ट्रेन की सही जानकारी नहीं भेजी।');$('notice').textContent=d.demo?'डेमो मोड — सारी ट्रेन जानकारी काल्पनिक है।':'लाइव सेवा से प्राप्त जानकारी — अपडेट का समय जाँचें।';$('name').textContent=t.number+' • '+t.name;$('route').textContent=t.routeName||'रूट उपलब्ध नहीं';$('stats').replaceChildren();for(const [k,v] of [['वर्तमान स्थिति',t.currentStation||'उपलब्ध नहीं'],['अगला स्टेशन',t.nextStation||'उपलब्ध नहीं'],['देरी',Number.isFinite(t.delayMinutes)?t.delayMinutes+' मिनट':'उपलब्ध नहीं']]){const e=text('div',k,'stat');e.append(text('b',v));$('stats').append(e)}const stamp=Date.parse(d.updatedAt);$('updated').textContent='डेटा का समय: '+(Number.isFinite(stamp)?new Date(stamp).toLocaleString('hi-IN'):'उपलब्ध नहीं')+(Date.now()-stamp>300000?' • पुराना अपडेट':'');$('nearby').replaceChildren();const valid=(d.nearby||[]).filter(n=>n.number!==t.number&&n.corridorId&&n.corridorId===t.corridorId&&n.direction===t.direction&&[n.positionKm,t.positionKm,t.direction].every(Number.isFinite));valid.push({...t,self:true});valid.sort((a,b)=>(b.positionKm-a.positionKm)*(t.direction||1));for(const n of valid){const delta=(n.positionKm-t.positionKm)*t.direction;const e=text('div',n.self?'🚆 आपकी ट्रेन':n.number+' • '+n.name,'train'+(n.self?' self':''));if(!n.self)e.append(text('div',(delta>0?'आगे':delta<0?'पीछे':'लगभग समान स्थिति')+' • '+Math.abs(delta).toFixed(1)+' किमी • '+(n.estimated?'अनुमानित':'रिपोर्ट की गई रूट स्थिति'),'badge'));$('nearby').append(e)}if(valid.length===1)$('nearby').append(text('p','आगे–पीछे की ट्रेनों का तुलनीय डेटा उपलब्ध नहीं है।'));$('stations').replaceChildren();for(const s of d.stations||[])$('stations').append(text('div',s.name+' • '+(s.status||'स्थिति उपलब्ध नहीं'),'station'));$('result').hidden=false}
async function search(q){$('message').replaceChildren();$('result').hidden=true;lastQuery=q;try{let d;{const base=new URL($('endpoint').value);if(base.protocol!=='https:')throw Error('सर्वर का HTTPS पता डालें।');const url=new URL(base.href.replace(/\/$/,'')+'/api/status');url.searchParams.set('train',q);url.searchParams.set('date',$('date').value);$('message').textContent='जानकारी आ रही है…';const r=await fetch(url,{signal:AbortSignal.timeout(15000)});d=await r.json();if(!r.ok)throw Error(d.error||'लाइव सेवा उपलब्ध नहीं');if(d.demo)throw Error('लाइव सेवा ने डेमो डेटा भेजा।');}render(d);$('message').replaceChildren()}catch(e){$('message').replaceChildren(text('div',e.message||'डेटा नहीं मिला','error'))}}
$('search').addEventListener('submit',e=>{e.preventDefault();search($('query').value.trim())});$('refresh').onclick=()=>search(lastQuery);$('mode').onchange=()=>{$('result').hidden=true;$('message').replaceChildren();$('notice').textContent=$('mode').value==='demo'?'डेमो मोड — काल्पनिक जानकारी।':'लाइव मोड — सर्वर का पता जोड़ें; अभी डेटा प्राप्त नहीं हुआ है।'};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

try{$('endpoint').value=localStorage.getItem('rail-server')||''}catch{}
$('endpoint').addEventListener('change',()=>{try{localStorage.setItem('rail-server',$('endpoint').value.trim())}catch{}});
