import {t,language,unavailable,liveUnavailable} from './i18n.js';
export const $=id=>document.getElementById(id);
export function el(tag,txt='',cls=''){const n=document.createElement(tag);n.textContent=txt;if(cls)n.className=cls;return n;}
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function time(v){if(!v)return '—';if(/^\d{2}:\d{2}$/.test(v))return v;const d=new Date(v);return Number.isFinite(+d)?new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).format(d):'—';}
export function fullTime(v){if(!v)return unavailable();const d=new Date(v);return Number.isFinite(+d)?new Intl.DateTimeFormat(language==='hi'?'hi-IN':'en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(d):String(v);}
export function fresh(stamp){const age=Date.now()-Date.parse(stamp);return Number.isFinite(age)&&age<=300000&&age>=-60000;}
export function age(stamp){const delta=Date.now()-Date.parse(stamp);if(!Number.isFinite(delta))return unavailable();if(delta< -60000)return t('अपडेट समय अमान्य','Invalid update time');const seconds=Math.max(0,Math.floor(delta/1000));return seconds<60?seconds+t(' सेकंड पहले',' seconds ago'):Math.floor(seconds/60)+t(' मिनट पहले',' minutes ago');}
export function status(delay){return Number.isFinite(delay)?{label:delay>0?'+'+delay+t(' मिनट देरी',' min Delay'):delay<0?Math.abs(delay)+t(' मिनट पहले',' min Early'):t('समय पर','On Time'),cls:delay>0?'late':'ontime'}:{label:unavailable(),cls:'muted'};}
export function badge(delay){const s=status(delay);return el('span',s.label,'pill '+s.cls);}
export function empty(target,message){target.replaceChildren(el('div',message,'empty'));}
export function meta(w){return w.mode==='schedule'?t('सेवा से प्राप्त समय-सारणी','Provider schedule'):t('आखिरी अपडेट: ','Last Updated: ')+age(w.updatedAt)+(fresh(w.updatedAt)?'':t(' • डेटा अपडेट होने में देरी हो सकती है',' • Data may be delayed'));}
export function errorBox(target,error,retry){const box=el('div','','error');box.setAttribute('role','alert');box.append(el('strong',liveUnavailable()));if(error?.status===429)box.append(el('p',t('डेटा सेवा की सीमा पूरी है। ','Data service limit reached. ')+(error.retryAfterSeconds||120)+t(' सेकंड बाद फिर कोशिश करें।',' seconds before retrying.')));if(error?.code==='UPGRADE_REQUIRED')box.append(el('p',t('सर्वर पर संस्करण 9.2 deploy करें, फिर दोबारा कनेक्ट करें।','Deploy server version 9.2, then reconnect.')));else if(error?.name==='TimeoutError')box.append(el('p',t('सर्वर जवाब देने में समय ले रहा है। फिर कोशिश करें।','The server is taking too long. Please retry.')));else if(error?.status!==429)box.append(el('p',t('ताज़ा लाइव रिपोर्ट नहीं मिली। कुछ देर बाद फिर कोशिश करें।','No fresh live report was available. Please retry shortly.')));const b=el('button',t('↻ फिर कोशिश करें','↻ Retry'),'secondary');b.onclick=retry;if(error?.status===429){const end=error.retryAt??(Date.now()+(error.retryAfterSeconds??120)*1000);const message=box.querySelector('p');const update=()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));b.disabled=left>0;b.textContent=left?t('फिर कोशिश करें • ','Retry • ')+left+'s':t('↻ फिर कोशिश करें','↻ Retry');if(message)message.textContent=left?t('डेटा सेवा की सीमा पूरी है। ','Data service limit reached. ')+left+t(' सेकंड बाद फिर कोशिश करें।',' seconds before retrying.'):t('प्रतीक्षा पूरी हुई। फिर कोशिश कर सकते हैं; डेटा मिलना सेवा की उपलब्धता पर निर्भर है।','Wait complete. You can retry; data still depends on service availability.');return left;};update();const tick=setInterval(()=>{if(!box.isConnected||!update())clearInterval(tick);},1000);}box.append(b);target.replaceChildren(box);}
export function field(label,value,cls=''){const n=el('div','','fact');n.append(el('small',label),el('strong',value??unavailable(),cls));return n;}
export function events(arrival,departure){const grid=el('div','','event-grid');for(const [label,event]of [[t('आगमन','Arrival'),arrival],[t('प्रस्थान','Departure'),departure]]){const box=el('div');box.append(el('small',label),el('div',time(event?.scheduled),'normal-time'),el('small',event?.actual?t('दर्ज ','Actual ')+time(event.actual):t('संभावित ','Expected ')+time(event?.expected),'normal-time'));grid.append(box);}return grid;}
